name: Publish Michel.coffee Docker Image

on:
  push:
    branches:
      - base

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GH Registry
        run: echo ${{secrets.PKGS_LOGIN_PASS}} | docker login https://ghcr.io -u Simorenarium --password-stdin

      - name: Build the Docker image
        run: docker build . -t ghcr.io/simorenarium/michel.coffee/website:${{ github.run_id }} -t ghcr.io/simorenarium/michel.coffee/website:latest

      - name: Push Docker - run id
        run: docker push ghcr.io/simorenarium/michel.coffee/website:${{ github.run_id }}

      - name: Push Docker - latest
        run: docker push ghcr.io/simorenarium/michel.coffee/website:latest
