name: Publish Ogma Docker Image

on:
  push:
    branches:
      - base

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GH Registry
        run: echo ${{secrets.PKGS_LOGIN_PASS}} | docker login https://docker.pkg.github.com -u Simorenarium --password-stdin

      - name: Build the Docker image
        run: cd bot && docker build . -t docker.pkg.github.com/simorenarium/michel.coffee/website:${{ github.run_id }} -t docker.pkg.github.com/simorenarium/michel.coffee/website:latest

      - name: Push Docker - run id
        run: docker push docker.pkg.github.com/simorenarium/michel.coffee/website:${{ github.run_id }}

      - name: Push Docker - latest
        run: docker push docker.pkg.github.com/simorenarium/michel.coffee/website:latest
